version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: socialai
      POSTGRES_USER: social
      POSTGRES_PASSWORD: socialpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build:
      context: backend
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgres://social:socialpass@postgres:5432/socialai
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    ports: ["3000:3000"]

volumes:
  pgdata:
